const standardDeck = [
  { value: "A", suit: "hearts", emoji: "🂱", suitEmoji: "♥️" },
  { value: "2", suit: "hearts", emoji: "🂲", suitEmoji: "♥️" },
  { value: "3", suit: "hearts", emoji: "🂳", suitEmoji: "♥️" },
  { value: "4", suit: "hearts", emoji: "🂴", suitEmoji: "♥️" },
  { value: "5", suit: "hearts", emoji: "🂵", suitEmoji: "♥️" },
  { value: "6", suit: "hearts", emoji: "🂶", suitEmoji: "♥️" },
  { value: "7", suit: "hearts", emoji: "🂷", suitEmoji: "♥️" },
  { value: "8", suit: "hearts", emoji: "🂸", suitEmoji: "♥️" },
  { value: "9", suit: "hearts", emoji: "🂹", suitEmoji: "♥️" },
  { value: "10", suit: "hearts", emoji: "🂺", suitEmoji: "♥️" },
  { value: "J", suit: "hearts", emoji: "🂻", suitEmoji: "♥️" },
  { value: "Q", suit: "hearts", emoji: "🂽", suitEmoji: "♥️" },
  { value: "K", suit: "hearts", emoji: "🂾", suitEmoji: "♥️" },
  { value: "A", suit: "spades", emoji: "🃁", suitEmoji: "♠️" },
  { value: "2", suit: "spades", emoji: "🃂", suitEmoji: "♠️" },
  { value: "3", suit: "spades", emoji: "🃃", suitEmoji: "♠️" },
  { value: "4", suit: "spades", emoji: "🃄", suitEmoji: "♠️" },
  { value: "5", suit: "spades", emoji: "🃅", suitEmoji: "♠️" },
  { value: "6", suit: "spades", emoji: "🃆", suitEmoji: "♠️" },
  { value: "7", suit: "spades", emoji: "🃇", suitEmoji: "♠️" },
  { value: "8", suit: "spades", emoji: "🃈", suitEmoji: "♠️" },
  { value: "9", suit: "spades", emoji: "🃉", suitEmoji: "♠️" },
  { value: "10", suit: "spades", emoji: "🃊", suitEmoji: "♠️" },
  { value: "J", suit: "spades", emoji: "🃋", suitEmoji: "♠️" },
  { value: "Q", suit: "spades", emoji: "🃌", suitEmoji: "♠️" },
  { value: "K", suit: "spades", emoji: "🃍", suitEmoji: "♠️" },
  { value: "A", suit: "clubs", emoji: "🃑", suitEmoji: "♣️" },
  { value: "2", suit: "clubs", emoji: "🃒", suitEmoji: "♣️" },
  { value: "3", suit: "clubs", emoji: "🃓", suitEmoji: "♣️" },
  { value: "4", suit: "clubs", emoji: "🃔", suitEmoji: "♣️" },
  { value: "5", suit: "clubs", emoji: "🃕", suitEmoji: "♣️" },
  { value: "6", suit: "clubs", emoji: "🃖", suitEmoji: "♣️" },
  { value: "7", suit: "clubs", emoji: "🃗", suitEmoji: "♣️" },
  { value: "8", suit: "clubs", emoji: "🃘", suitEmoji: "♣️" },
  { value: "9", suit: "clubs", emoji: "🃙", suitEmoji: "♣️" },
  { value: "10", suit: "clubs", emoji: "🃚", suitEmoji: "♣️" },
  { value: "J", suit: "clubs", emoji: "🃛", suitEmoji: "♣️" },
  { value: "Q", suit: "clubs", emoji: "🃝", suitEmoji: "♣️" },
  { value: "K", suit: "clubs", emoji: "🃞", suitEmoji: "♣️" },
  { value: "A", suit: "diamonds", emoji: "🃁", suitEmoji: "♦️" },
  { value: "2", suit: "diamonds", emoji: "🃂", suitEmoji: "♦️" },
  { value: "3", suit: "diamonds", emoji: "🃃", suitEmoji: "♦️" },
  { value: "4", suit: "diamonds", emoji: "🃄", suitEmoji: "♦️" },
  { value: "5", suit: "diamonds", emoji: "🃅", suitEmoji: "♦️" },
  { value: "6", suit: "diamonds", emoji: "🃆", suitEmoji: "♦️" },
  { value: "7", suit: "diamonds", emoji: "🃇", suitEmoji: "♦️" },
  { value: "8", suit: "diamonds", emoji: "🃈", suitEmoji: "♦️" },
  { value: "9", suit: "diamonds", emoji: "🃉", suitEmoji: "♦️" },
  { value: "10", suit: "diamonds", emoji: "🃊", suitEmoji: "♦️" },
  { value: "J", suit: "diamonds", emoji: "🃋", suitEmoji: "♦️" },
  { value: "Q", suit: "diamonds", emoji: "🃍", suitEmoji: "♦️" },
  { value: "K", suit: "diamonds", emoji: "🃎", suitEmoji: "♦️" },
];

export default standardDeck;
